In [2]:
import numpy as np
import pandas as pd

In [13]:

class HashTable:

    # set up the hash table, with no values in it
    def __init__(self):
        self.size = 0
        self.table = [None]*self.size

    # given some input, figure out its hash values
    # * You may use python hash() in this method
    def __getKey(self, x):
        return len(x)%len(self.table)
        
    # rehash the table if it is not of appropriate size
    # * Rehashing is required for this assignment, though this is private
    # * I reserve the write to change the parameters of random list generation in autograder to force rehashing
    def __rehash(self):
        l = []
        for x in self.table:
            if x!=None:
                for y in x:
                    l.append(y)
        if self.size>len(self.table)//2:
             self.table = [None]*(len(self.table)*2)
        if self.size<len(self.table)//4:
            self.table = [None]*(len(self.table)/2)
        
        for x in l:
            self.insert(x)
        
            
    
    def insert(self, x):
        if len(self.table)==0:
            self.table = [None,None,None,None]
            loc = self.__getKey(x[0])
            self.table[loc] = [x]
            self.table[loc][0][2] = [self.table[loc][0][2]]
            self.size+=1
            
            
        else:
            loc = self.__getKey(x[0])
            if self.table[loc] ==None:
                self.table[loc] = [x]
                self.table[loc][0][2] = [self.table[loc][0][2]]
            else:
                if self.contains(x[0])==True:
                    for i in range(0,len(self.table[loc])):
                        if self.table[loc][i][0]==x[0]:
                            self.table[loc][i][2].append(x[2])
                if self.contains(x[0])==False:
                    self.table[loc].append(x)
                    self.table[loc][-1][2] = [self.table[loc][-1][2]]
                    
                        
                if self.size>len(self.table)//2:
                    self.__rehash()
    def returnVal(self,x):
        if self.contains(x):
            loc = self.__getKey(x)
            for y in self.table[loc]:
                if y[0]==x:
                    return y
        else:
            return False
        
   
                
        
    # remove x from the hash table
    def remove(self, x):
        loc = self.__getKey(x)
        if self.table[loc]==None:
            return 
        for i in range(len(self.table[loc])):
            if self.table[loc][i]==x:
                self.table[loc].pop(i)
                self.size-= 1
                if self.size<len(self.table)//4:
                    self.__rehash()
            return
        return
        
                
                
    # check if x is in the hash table
    def contains(self, x):
        if len(self.table)==0:
            return False
        loc = self.__getKey(x)
        if self.table[loc] == None:
            return False
        for i in range(0,len(self.table[loc])):
            if self.table[loc][i][0]==x:
                return True
        return False

class Donation:
    
    def __init__(self,file):
        self.data = pd.read_csv(file, sep = ',')
        
        
        self.names = self.data['contributor_name'].tolist()
        self.donees = self.data['committee_name'].tolist()
        self.donationAmount = self.data['contribution_receipt_amount'].tolist()
        for i in range(0,len(self.donationAmount)):
            self.donationAmount[i] = int(self.donationAmount[i])
        
        self.donation = []
        self.l = HashTable()
        for i in range(0,len(self.names)):
            self.donation.append([self.names[i],self.donees[i],self.donationAmount[i]])
        for x in self.donation:
            self.l.insert(x)
            
    def donations(self):
        return self.l.table
    def contains(self,x):
        return self.l.contains(x)
    def insert(self,x):
        self.l.insert(x)
    def allDon(self,x):
        z = self.l.returnVal(x)
        amount = ""
        totamount = 0
        if z != False:
            for money in z[2]:
                amount = amount + "$"+str(money)+", "
                totamount+=money
                
            return x+":"+amount+" total amount:$"+str(totamount)

In [18]:
x = Donation('dataset.csv')

In [19]:
x.allDon('NELSON, JEFFREY')

'NELSON, JEFFREY:$8, $10, $1, $1, $10, $25, $2, $1, $10, $1, $10, $50, $10, $2, $25, $5, $10, $1, $25, $1, $25, $2, $10, $10, $25, $11, $11, $8, $10, $25, $10, $10, $10, $25, $25, $11, $25, $10, $10, $15, $1, $10, $1, $10, $1, $10, $11, $1, $1, $10, $1, $10, $1, $10, $25, $2, $25, $1, $10, $1, $10, $1, $1, $10, $11, $1, $25, $1, $10, $1, $10, $1, $10, $1, $10, $1, $25, $1, $10, $1, $1, $10, $15, $1, $1, $25, $1, $10, $1, $10, $1, $10, $1, $10, $11, $1, $10, $1, $10, $1, $10, $1, $10, $1, $25, $1, $10, $1, $10, $1, $10, $1, $25, $1, $10, $1, $10, $11, $1, $11, $1, $25, $2, $1, $10, $1, $10, $1, $10, $1, $11, $25, $25, $11, $11, $11, $25, $25, $2, $8, $8,  total amount:$1285'

In [20]:
x.donations()

[[['BEVILLE, CLAUDIA', 'ACTBLUE', [5, 25, 25]],
  ['VICKERY, KIMBALL',
   'GEORGIANS FOR KELLY LOEFFLER',
   [6,
    10,
    7,
    2,
    10,
    5,
    7,
    30,
    20,
    10,
    5,
    5,
    20,
    10,
    6,
    7,
    30,
    2,
    12,
    10,
    5,
    15,
    10,
    20,
    20,
    10,
    3,
    20,
    10,
    7,
    10,
    10,
    12]],
  ['SMITH, DANNA', 'WINRED', [15]],
  ['D., JOSEFINA', 'WINRED', [50, 5]],
  ['VALDEZ, KATHLEEN', 'ACTBLUE', [25, 10, 1, 30, 3]],
  ['NELSON, JEFF', 'ACTBLUE', [10, 1, 10, 1, 10, 1, 10, 1, 10, 1, 10, 1]],
  ['KING, HARDIN', 'ACTBLUE', [50, 5]],
  ['GEDDES, TYER', 'ACTBLUE', [5]],
  ['WALL, JEFFREY M.',
   'ROAD SPRINKLER FITTERS LOCAL UNION NO. 669, UA, AFL-CIO PAC',
   [28]],
  ['BUTSCH, JAMES F. MR.', 'NRSC', [201, 201]]],
 [['BUTSCH, JAMES', 'NRCC', [150, 100, 151, 300]],
  ['REUTOV, ANTON',
   'WINRED',
   [50,
    35,
    35,
    25,
    35,
    35,
    25,
    25,
    25,
    25,
    25,
    25,
    25,
    25,
    25,
    35,
    35,
    50,
    20]],
  ['MEITH, SHERRY', 'ACTBLUE', [45, 45, 25]],
  ['STONE, ALISHA',
   'ACTBLUE',
   [6,
    6,
    1,
    6,
    1,
    10,
    1,
    10,
    10,
    1,
    0,
    4,
    1,
    10,
    0,
    4,
    1,
    10,
    2,
    0,
    4,
    25,
    1,
    10,
    0,
    4,
    1,
    10,
    1,
    10]],
  ['CARMACK, JENNIFER', 'WINRED', [5, 25]],
  ['HANSEN, NORMA', 'WINRED', [45, 45, 45, 45]],
  ['MILLER, JACQUELINE B.', 'REPUBLICAN NATIONAL COMMITTEE', [90, 200]],
  ['HOLMES, NANCY', 'ACTBLUE', [10, 1, 10, 10, 10, 6, 1]],
  ['VALDEZ, KATHY', 'ACTBLUE', [15, 15, 15, 3, 35, 30, 12, 12, 25, 20, 20]],
  ['MURRAY, BRUCE', 'ACTBLUE', [15]],
  ['REYNOLDS, YVONNE MISS',
   'SEAL PAC SUPPORTING ELECTING AMERICAN LEADERS PAC',
   [70]]],
 [['DWORAK, MELVIN',
   'DEMOCRATIC PARTY OF OREGON',
   [5, 5, 5, 7, 5, 5, 3, 5, 10, 5, 5]],
  ['ALLEN, JUANA C', 'NEW PAC', [22]],
  ['FESSLER, DEBRA', 'WINRED', [2]],
  ['HUMPHREYS, RICHARD', 'WINRED', [100]],
  ['GARCIACOBB, JO', 'WINRED', [20]],
  ['KOHLER, MARY M', 'ACTBLUE', [25, 50, 5]],
  ['ROOD, NEIL', 'ACTBLUE', [100]],
  ['SNYDER, WESLEY', 'ANGELA FOR OREGON', [100]]],
 [['GALVEZ JR, FRANCISCO JAVIER',
   'D.R.I.V.E. - DEMOCRAT, REPUBLICAN, INDEPENDENT VOTER EDUCATION (THE PAC OF THE INTERNATIONAL BROTHERHOOD OF TEAMSTERS)',
   [5, 15, 5, 5, 5]],
  ['PURDY, KENT', 'TIM SCOTT FOR SENATE', [25, 25, 25, 100, 20]],
  ['BOCHSLER, ROBIN',
   'ACTBLUE',
   [5, 10, 10, 10, 5, 1, 1, 1, 1, 1, 1, 5, 5, 10, 5, 35]],
  ['SCHMIDTMAN, JESSICA', 'ACTBLUE', [25, 1, 1, 1, 1, 1, 5]],
  ['NELSON, JEFFREY',
   'ACTBLUE',
   [8,
    10,
    1,
    1,
    10,
    25,
    2,
    1,
    10,
    1,
    10,
    50,
    10,
    2,
    25,
    5,
    10,
    1,
    25,
    1,
    25,
    2,
    10,
    10,
    25,
    11,
    11,
    8,
    10,
    25,
    10,
    10,
    10,
    25,
    25,
    11,
    25,
    10,
    10,
    15,
    1,
    10,
    1,
    10,
    1,
    10,
    11,
    1,
    1,
    10,
    1,
    10,
    1,
    10,
    25,
    2,
    25,
    1,
    10,
    1,
    10,
    1,
    1,
    10,
    11,
    1,
    25,
    1,
    10,
    1,
    10,
    1,
    10,
    1,
    10,
    1,
    25,
    1,
    10,
    1,
    1,
    10,
    15,
    1,
    1,
    25,
    1,
    10,
    1,
    10,
    1,
    10,
    1,
    10,
    11,
    1,
    10,
    1,
    10,
    1,
    10,
    1,
    10,
    1,
    25,
    1,
    10,
    1,
    10,
    1,
    10,
    1,
    25,
    1,
    10,
    1,
    10,
    11,
    1,
    11,
    1,
    25,
    2,
    1,
    10,
    1,
    10,
    1,
    10,
    1,
    11,
    25,
    25,
    11,
    11,
    11,
    25,
    25,
    2,
    8,
    8]],
  ['COBB, KEITH', 'WINRED', [50, 5, 5, 5, 5, 5, 50]],
  ['VALDEZ, KATHLEEN L.', 'DEMOCRATIC PARTY OF OREGON', [30]],
  ['FARRIS, TIM', 'ACTBLUE', [1, 1, 7, 10]],
  ['SCHNEIDER, CURT', 'ACTBLUE', [25, 50, 50, 25, 10]],
  ['CALDWELL, BETTY',
   'ACTBLUE',
   [6, 6, 6, 6, 1, 10, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 1, 6]],
  ['WALL, PETER', 'ACTBLUE', [50, 5]],
  ['BALOG, FLORENCE', 'DSCC', [100, 50]]]]

In [21]:
data = pd.read_csv('dataset.csv', sep = ',')

In [23]:
data.describe()

,report_year,image_number,file_number,committee_name.1,contributor_suffix,contributor_zip,memo_code_full,contribution_receipt_amount,contributor_aggregate_ytd,candidate_id,...,conduit_committee_city,conduit_committee_state,conduit_committee_zip,donor_committee_name,fec_election_year,original_sub_id,link_id,two_year_transaction_period,increased_limit,sub_id
count,380.0,3.800000e+02,3.800000e+02,0.0,0.0,3.800000e+02,0.0,380.000000,380.000000,0.0,...,0.0,0.0,0.0,0.0,40.00000,0.0,3.800000e+02,380.0,0.0,3.800000e+02
mean,2021.0,2.021069e+17,1.529204e+06,NaN,NaN,3.024035e+08,NaN,16.593211,100.358684,NaN,...,NaN,NaN,NaN,NaN,2020.92500,NaN,4.072501e+18,2022.0,NaN,4.076796e+18
std,0.0,2.002693e+12,1.216807e+04,NaN,NaN,4.510542e+08,NaN,29.475739,132.164380,NaN,...,NaN,NaN,NaN,NaN,0.79703,NaN,2.105904e+16,0.0,NaN,1.888829e+16
min,2021.0,2.021020e+17,1.498693e+06,NaN,NaN,9.736200e+04,NaN,0.400000,1.420000,NaN,...,NaN,NaN,NaN,NaN,2020.00000,NaN,4.020920e+18,2022.0,NaN,4.031520e+18
25%,2021.0,2.021073e+17,1.532732e+06,NaN,NaN,9.736200e+04,NaN,2.500000,19.250000,NaN,...,NaN,NaN,NaN,NaN,2020.00000,NaN,4.073120e+18,2022.0,NaN,4.082320e+18
50%,2021.0,2.021073e+17,1.533121e+06,NaN,NaN,9.736200e+04,NaN,10.000000,60.000000,NaN,...,NaN,NaN,NaN,NaN,2021.00000,NaN,4.080120e+18,2022.0,NaN,4.082520e+18
75%,2021.0,2.021073e+17,1.533121e+06,NaN,NaN,9.736207e+08,NaN,20.000000,100.000000,NaN,...,NaN,NaN,NaN,NaN,2022.00000,NaN,4.080120e+18,2022.0,NaN,4.082520e+18
max,2021.0,2.021112e+17,1.550046e+06,NaN,NaN,9.736298e+08,NaN,300.000000,851.000000,NaN,...,NaN,NaN,NaN,NaN,2022.00000,NaN,4.112520e+18,2022.0,NaN,4.120220e+18